// <auto-generated />
using HospitalManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220327063134_setPrimaryKey")]
    partial class setPrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalManagementSystem.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            City = "Nagpur",
                            Description = "Heart Specialist",
                            Email = "abc@gmail.com",
                            Mobile = 9881943266L,
                            Name = "Spandan",
                            Photo = "2.jpg"
                        },
                        new
                        {
                            HospitalId = 2,
                            City = "Delhi",
                            Description = "Brain Specialist",
                            Email = "Wockheart@gmail.com",
                            Mobile = 9021910763L,
                            Name = "Wockheart",
                            Photo = "2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
